"""fase3_token_revoked_at

Revision ID: 5bd6624cda20
Revises: a02c8f7825ad
Create Date: 2026-04-09 08:20:00.454432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bd6624cda20'
down_revision: Union[str, Sequence[str], None] = 'a02c8f7825ad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('token_revoked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_revoked_at')
    # ### end Alembic commands ###
