"""fase4_indices

Revision ID: b2dfc7cf6f1a
Revises: 5bd6624cda20
Create Date: 2026-04-09 09:25:32.947532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2dfc7cf6f1a'
down_revision: Union[str, Sequence[str], None] = '5bd6624cda20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_cash_movements_cash_session_id'), 'cash_movements', ['cash_session_id'], unique=False)
    op.create_index(op.f('ix_credit_sales_customer_id'), 'credit_sales', ['customer_id'], unique=False)
    op.create_index('ix_credits_created', 'credits', ['created_at'], unique=False)
    op.create_index('ix_credits_customer_type', 'credits', ['customer_id', 'type'], unique=False)
    op.create_index(op.f('ix_sales_created_at'), 'sales', ['created_at'], unique=False)
    op.create_index('ix_sales_created_status', 'sales', ['created_at', 'status'], unique=False)
    op.create_index('ix_sales_status', 'sales', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_status', table_name='sales')
    op.drop_index('ix_sales_created_status', table_name='sales')
    op.drop_index(op.f('ix_sales_created_at'), table_name='sales')
    op.drop_index('ix_credits_customer_type', table_name='credits')
    op.drop_index('ix_credits_created', table_name='credits')
    op.drop_index(op.f('ix_credit_sales_customer_id'), table_name='credit_sales')
    op.drop_index(op.f('ix_cash_movements_cash_session_id'), table_name='cash_movements')
    # ### end Alembic commands ###
