"""initial_schema

Revision ID: efd19c998f1c
Revises: 
Create Date: 2026-04-15 10:42:35.259957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'efd19c998f1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('api_key_encrypted', sa.Text(), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('max_tokens', sa.Integer(), nullable=False),
    sa.Column('temperature', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('custom_prompt', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cabys',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=1500), nullable=True),
    sa.Column('iva', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('cabys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cabys_code'), ['code'], unique=False)

    op.create_table('cash_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('terminal_id', sa.String(length=10), nullable=False),
    sa.Column('opening_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('closing_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('expected_closing', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('difference', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('closed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('date', 'terminal_id', name='uq_cash_date_terminal')
    )
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_sessions_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_sessions_id'), ['id'], unique=False)

    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('icon', sa.String(length=10), nullable=True),
    sa.Column('position', sa.Integer(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_categories_id'), ['id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('secondary_phone', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=200), nullable=True),
    sa.Column('id_type', sa.String(length=20), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('customer_type', sa.String(length=20), nullable=True),
    sa.Column('province_id', sa.String(length=2), nullable=True),
    sa.Column('province_name', sa.String(length=50), nullable=True),
    sa.Column('canton_id', sa.String(length=2), nullable=True),
    sa.Column('canton_name', sa.String(length=80), nullable=True),
    sa.Column('district_id', sa.String(length=2), nullable=True),
    sa.Column('district_name', sa.String(length=80), nullable=True),
    sa.Column('neighborhood', sa.String(length=80), nullable=True),
    sa.Column('credit_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('has_credit_limit', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('last_purchase_date', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('commercial_name', sa.String(length=80), nullable=True),
    sa.Column('otras_senas_extranjero', sa.String(length=300), nullable=True),
    sa.Column('phone_country_code', sa.String(length=3), nullable=True),
    sa.Column('otras_senas', sa.String(length=160), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id_number'), ['id_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)

    op.create_table('dashboard_daily_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('sales_today', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('estimated_profit_today', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('critical_products', sa.Integer(), nullable=False),
    sa.Column('credits_receivable', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('pending_purchases', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash_expected', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cash_difference', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dashboard_daily_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dashboard_daily_snapshots_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_dashboard_daily_snapshots_snapshot_date'), ['snapshot_date'], unique=True)

    op.create_table('document_sequences',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('branch_code', sa.String(length=3), nullable=False),
    sa.Column('terminal_code', sa.String(length=5), nullable=False),
    sa.Column('document_type', sa.String(length=2), nullable=False),
    sa.Column('next_number', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('branch_code', 'terminal_code', 'document_type', name='uq_branch_terminal_doctype')
    )
    op.create_table('economic_activities',
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    with op.batch_alter_table('economic_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_economic_activities_code'), ['code'], unique=False)

    op.create_table('issuer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('legal_name', sa.String(length=120), nullable=False),
    sa.Column('commercial_name', sa.String(length=120), nullable=True),
    sa.Column('id_type', sa.String(length=2), nullable=False),
    sa.Column('id_number', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('provider_system_id', sa.String(length=20), nullable=True),
    sa.Column('economic_activity_code', sa.String(length=6), nullable=True),
    sa.Column('provincia', sa.String(length=1), nullable=True),
    sa.Column('canton', sa.String(length=2), nullable=True),
    sa.Column('distrito', sa.String(length=2), nullable=True),
    sa.Column('barrio', sa.String(length=50), nullable=True),
    sa.Column('otras_senas', sa.String(length=250), nullable=True),
    sa.Column('branch_code', sa.String(length=3), nullable=False),
    sa.Column('terminal_code', sa.String(length=5), nullable=False),
    sa.Column('enable_rep', sa.Integer(), nullable=False),
    sa.Column('rep_default_condicion_venta', sa.String(length=2), nullable=True),
    sa.Column('rep_default_codigo_referencia', sa.String(length=2), nullable=True),
    sa.Column('phone_country_code', sa.String(length=3), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('issuer_profiles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_issuer_profiles_id'), ['id'], unique=False)

    op.create_table('payment_methods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_methods_id'), ['id'], unique=False)

    op.create_table('secure_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value_encrypted', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('secure_config', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_secure_config_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_secure_config_key'), ['key'], unique=True)

    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default='1', nullable=False),
    sa.Column('contact_name', sa.String(length=120), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('contact_position', sa.String(length=80), nullable=True),
    sa.Column('id_type', sa.String(length=2), nullable=True),
    sa.Column('id_number', sa.String(length=20), nullable=True),
    sa.Column('commercial_name', sa.String(length=80), nullable=True),
    sa.Column('provincia', sa.String(length=1), nullable=True),
    sa.Column('canton', sa.String(length=2), nullable=True),
    sa.Column('distrito', sa.String(length=2), nullable=True),
    sa.Column('barrio', sa.String(length=50), nullable=True),
    sa.Column('otras_senas', sa.String(length=250), nullable=True),
    sa.Column('otras_senas_extranjero', sa.String(length=300), nullable=True),
    sa.Column('phone_country_code', sa.String(length=3), nullable=True),
    sa.Column('economic_activity_code', sa.String(length=6), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_suppliers_id'), ['id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('permissions', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('token_revoked_at', sa.DateTime(), nullable=True),
    sa.Column('must_change_password', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('cash_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cash_session_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=3), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('reference_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cash_movements_cash_session_id'), ['cash_session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cash_movements_id'), ['id'], unique=False)

    op.create_table('credits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.create_index('ix_credits_created', ['created_at'], unique=False)
        batch_op.create_index('ix_credits_customer_type', ['customer_id', 'type'], unique=False)
        batch_op.create_index(batch_op.f('ix_credits_id'), ['id'], unique=False)

    op.create_table('customer_economic_activity',
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('activity_code', sa.String(length=10), nullable=False),
    sa.ForeignKeyConstraint(['activity_code'], ['economic_activities.code'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('customer_id', 'activity_code')
    )
    op.create_table('expenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_id'), ['id'], unique=False)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('barcode', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('cabys_code', sa.String(length=50), nullable=True),
    sa.Column('cabys_name', sa.String(length=500), nullable=True),
    sa.Column('tax_type', sa.String(length=100), nullable=True),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('supplier_id', sa.Integer(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('cost', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('stock', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('min_stock', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('unit_type', sa.String(length=10), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_pos_favorite', sa.Boolean(), nullable=True),
    sa.Column('registro_fiscal_8707', sa.String(length=12), nullable=True),
    sa.Column('tax_tarifa_code_override', sa.String(length=2), nullable=True),
    sa.Column('partida_arancelaria', sa.String(length=12), nullable=True),
    sa.Column('impuesto_code', sa.String(length=2), nullable=True),
    sa.Column('factor_calculo_iva', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('tipo_transaccion', sa.String(length=2), nullable=True),
    sa.Column('numero_vin_serie', sa.String(length=17), nullable=True),
    sa.Column('registro_medicamento', sa.String(length=100), nullable=True),
    sa.Column('forma_farmaceutica', sa.String(length=3), nullable=True),
    sa.Column('iva_cobrado_fabrica', sa.String(length=2), nullable=True),
    sa.Column('discount_code_default', sa.String(length=2), nullable=True),
    sa.Column('imp_esp_impuesto_unidad', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('imp_esp_porcentaje', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('imp_esp_volumen_unidad_consumo', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('imp_esp_cantidad_unidad_medida', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_barcode'), ['barcode'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_code'), ['code'], unique=True)
        batch_op.create_index(batch_op.f('ix_products_id'), ['id'], unique=False)

    op.create_table('purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=50), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.Enum('pendiente', 'recibido', 'parcial', 'pagado', 'vencido', name='purchasestatus'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('pdf_path', sa.String(length=255), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.Date(), nullable=True),
    sa.Column('received_at', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchases_id'), ['id'], unique=False)

    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('cash_session_id', sa.Integer(), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('payment_method', sa.String(length=20), nullable=False),
    sa.Column('condicion_venta_code', sa.String(length=2), nullable=True),
    sa.Column('document_type', sa.String(length=2), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=True),
    sa.Column('moneda_code', sa.String(length=3), nullable=True),
    sa.Column('tipo_cambio', sa.String(length=20), nullable=True),
    sa.Column('condicion_venta_otros', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['cash_session_id'], ['cash_sessions.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_created_at'), ['created_at'], unique=False)
        batch_op.create_index('ix_sales_created_status', ['created_at', 'status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_id'), ['id'], unique=False)
        batch_op.create_index('ix_sales_status', ['status'], unique=False)

    op.create_table('settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('business_name', sa.String(length=200), nullable=True),
    sa.Column('legal_name', sa.String(length=200), nullable=True),
    sa.Column('id_type', sa.String(length=20), nullable=True),
    sa.Column('id_number', sa.String(length=50), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('logo_path', sa.String(length=300), nullable=True),
    sa.Column('default_tax', sa.String(length=10), nullable=True),
    sa.Column('default_supplier_id', sa.Integer(), nullable=True),
    sa.Column('rounding_enabled', sa.Boolean(), nullable=True),
    sa.Column('default_currency', sa.String(length=3), nullable=False),
    sa.Column('exchange_rate', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('printer_type', sa.String(length=20), nullable=True),
    sa.Column('printer_ip', sa.String(length=45), nullable=True),
    sa.Column('printer_port', sa.Integer(), nullable=True),
    sa.Column('cabys_last_update', sa.DateTime(), nullable=True),
    sa.Column('cabys_records', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['default_supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings_audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('changes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('credit_sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sale_id')
    )
    with op.batch_alter_table('credit_sales', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_sales_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_credit_sales_id'), ['id'], unique=False)

    op.create_table('electronic_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=2), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=True),
    sa.Column('consecutivo', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('xml_signed', sa.Text(), nullable=True),
    sa.Column('hacienda_response', sa.Text(), nullable=True),
    sa.Column('hacienda_status', sa.String(length=30), nullable=True),
    sa.Column('tries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('electronic_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_electronic_invoices_clave'), ['clave'], unique=True)
        batch_op.create_index(batch_op.f('ix_electronic_invoices_consecutivo'), ['consecutivo'], unique=True)
        batch_op.create_index(batch_op.f('ix_electronic_invoices_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_electronic_invoices_sale_id'), ['sale_id'], unique=False)

    op.create_table('electronic_reps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_payment_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=2), nullable=False),
    sa.Column('clave', sa.String(length=50), nullable=True),
    sa.Column('consecutivo', sa.String(length=20), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('xml_signed', sa.Text(), nullable=True),
    sa.Column('hacienda_response', sa.Text(), nullable=True),
    sa.Column('hacienda_status', sa.String(length=30), nullable=True),
    sa.Column('tries', sa.Integer(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['credit_payment_id'], ['credits.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('electronic_reps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_electronic_reps_clave'), ['clave'], unique=True)
        batch_op.create_index(batch_op.f('ix_electronic_reps_consecutivo'), ['consecutivo'], unique=True)
        batch_op.create_index(batch_op.f('ix_electronic_reps_credit_payment_id'), ['credit_payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_electronic_reps_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_electronic_reps_id'), ['id'], unique=False)

    op.create_table('inventory_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('venta', 'devolucion', 'entrada', 'ajuste', 'anulacion', name='movementtype'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_before', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('stock_after', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reference', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_movements_id'), ['id'], unique=False)

    op.create_table('proformas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('number', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=False),
    sa.Column('valid_until', sa.DateTime(), nullable=False),
    sa.Column('converted_sale_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['converted_sale_id'], ['sales.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proformas', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proformas_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_proformas_number'), ['number'], unique=True)

    op.create_table('purchase_credit_notes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity_returned', sa.DECIMAL(precision=12, scale=3), nullable=True),
    sa.Column('stock_reverted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_credit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_credit_notes_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_credit_notes_purchase_id'), ['purchase_id'], unique=False)

    op.create_table('purchase_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=12, scale=3), nullable=False),
    sa.Column('unit_cost', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('subtotal', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_details_id'), ['id'], unique=False)

    op.create_table('purchase_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['purchase_id'], ['purchases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('purchase_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_purchase_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_purchase_payments_purchase_id'), ['purchase_id'], unique=False)

    op.create_table('sale_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.Column('common_description', sa.String(length=200), nullable=True),
    sa.Column('discount_code', sa.String(length=2), nullable=True),
    sa.Column('discount_code_otro', sa.String(length=100), nullable=True),
    sa.Column('discount_description', sa.String(length=80), nullable=True),
    sa.Column('tipo_transaccion', sa.String(length=2), nullable=True),
    sa.Column('iva_cobrado_fabrica', sa.String(length=2), nullable=True),
    sa.Column('numero_vin_serie', sa.String(length=17), nullable=True),
    sa.Column('impuesto_code', sa.String(length=2), nullable=True),
    sa.Column('factor_calculo_iva', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('exon_tipo_doc', sa.String(length=2), nullable=True),
    sa.Column('exon_tipo_doc_otro', sa.String(length=100), nullable=True),
    sa.Column('exon_numero_doc', sa.String(length=40), nullable=True),
    sa.Column('exon_articulo', sa.Integer(), nullable=True),
    sa.Column('exon_inciso', sa.Integer(), nullable=True),
    sa.Column('exon_institucion', sa.String(length=2), nullable=True),
    sa.Column('exon_institucion_otro', sa.String(length=160), nullable=True),
    sa.Column('exon_fecha', sa.DateTime(), nullable=True),
    sa.Column('exon_tarifa', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_details_id'), ['id'], unique=False)

    op.create_table('supplier_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('last_purchase_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_preferred', sa.Boolean(), server_default='0', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('supplier_id', 'product_id', name='uq_supplier_product')
    )
    with op.batch_alter_table('supplier_products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_supplier_products_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_products_product_id'), ['product_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_supplier_products_supplier_id'), ['supplier_id'], unique=False)

    op.create_table('electronic_rep_references',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rep_id', sa.Integer(), nullable=False),
    sa.Column('electronic_invoice_id', sa.Integer(), nullable=False),
    sa.Column('amount_applied', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['electronic_invoice_id'], ['electronic_invoices.id'], ),
    sa.ForeignKeyConstraint(['rep_id'], ['electronic_reps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('electronic_rep_references', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_electronic_rep_references_electronic_invoice_id'), ['electronic_invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_electronic_rep_references_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_electronic_rep_references_rep_id'), ['rep_id'], unique=False)

    op.create_table('proforma_details',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=18, scale=5), nullable=False),
    sa.Column('tax_rate', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=5), nullable=True),
    sa.Column('is_common', sa.Boolean(), nullable=False),
    sa.Column('common_description', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['proforma_id'], ['proformas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('proforma_details', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_proforma_details_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proforma_details_id'))

    op.drop_table('proforma_details')
    with op.batch_alter_table('electronic_rep_references', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_electronic_rep_references_rep_id'))
        batch_op.drop_index(batch_op.f('ix_electronic_rep_references_id'))
        batch_op.drop_index(batch_op.f('ix_electronic_rep_references_electronic_invoice_id'))

    op.drop_table('electronic_rep_references')
    with op.batch_alter_table('supplier_products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_supplier_products_supplier_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_products_product_id'))
        batch_op.drop_index(batch_op.f('ix_supplier_products_id'))

    op.drop_table('supplier_products')
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_details_id'))

    op.drop_table('sale_details')
    with op.batch_alter_table('purchase_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_payments_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_payments_id'))

    op.drop_table('purchase_payments')
    with op.batch_alter_table('purchase_details', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_details_id'))

    op.drop_table('purchase_details')
    with op.batch_alter_table('purchase_credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_credit_notes_purchase_id'))
        batch_op.drop_index(batch_op.f('ix_purchase_credit_notes_id'))

    op.drop_table('purchase_credit_notes')
    with op.batch_alter_table('proformas', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_proformas_number'))
        batch_op.drop_index(batch_op.f('ix_proformas_id'))

    op.drop_table('proformas')
    with op.batch_alter_table('inventory_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_movements_id'))

    op.drop_table('inventory_movements')
    with op.batch_alter_table('electronic_reps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_electronic_reps_id'))
        batch_op.drop_index(batch_op.f('ix_electronic_reps_customer_id'))
        batch_op.drop_index(batch_op.f('ix_electronic_reps_credit_payment_id'))
        batch_op.drop_index(batch_op.f('ix_electronic_reps_consecutivo'))
        batch_op.drop_index(batch_op.f('ix_electronic_reps_clave'))

    op.drop_table('electronic_reps')
    with op.batch_alter_table('electronic_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_electronic_invoices_sale_id'))
        batch_op.drop_index(batch_op.f('ix_electronic_invoices_id'))
        batch_op.drop_index(batch_op.f('ix_electronic_invoices_consecutivo'))
        batch_op.drop_index(batch_op.f('ix_electronic_invoices_clave'))

    op.drop_table('electronic_invoices')
    with op.batch_alter_table('credit_sales', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_sales_id'))
        batch_op.drop_index(batch_op.f('ix_credit_sales_customer_id'))

    op.drop_table('credit_sales')
    op.drop_table('settings_audit_log')
    op.drop_table('settings')
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_index('ix_sales_status')
        batch_op.drop_index(batch_op.f('ix_sales_id'))
        batch_op.drop_index('ix_sales_created_status')
        batch_op.drop_index(batch_op.f('ix_sales_created_at'))

    op.drop_table('sales')
    with op.batch_alter_table('purchases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchases_id'))

    op.drop_table('purchases')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_id'))
        batch_op.drop_index(batch_op.f('ix_products_code'))
        batch_op.drop_index(batch_op.f('ix_products_barcode'))

    op.drop_table('products')
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_id'))

    op.drop_table('expenses')
    op.drop_table('customer_economic_activity')
    with op.batch_alter_table('credits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credits_id'))
        batch_op.drop_index('ix_credits_customer_type')
        batch_op.drop_index('ix_credits_created')

    op.drop_table('credits')
    with op.batch_alter_table('cash_movements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_movements_id'))
        batch_op.drop_index(batch_op.f('ix_cash_movements_cash_session_id'))

    op.drop_table('cash_movements')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))

    op.drop_table('users')
    with op.batch_alter_table('suppliers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_suppliers_id'))

    op.drop_table('suppliers')
    with op.batch_alter_table('secure_config', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_secure_config_key'))
        batch_op.drop_index(batch_op.f('ix_secure_config_id'))

    op.drop_table('secure_config')
    with op.batch_alter_table('payment_methods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_methods_id'))

    op.drop_table('payment_methods')
    with op.batch_alter_table('issuer_profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_issuer_profiles_id'))

    op.drop_table('issuer_profiles')
    with op.batch_alter_table('economic_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_economic_activities_code'))

    op.drop_table('economic_activities')
    op.drop_table('document_sequences')
    with op.batch_alter_table('dashboard_daily_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dashboard_daily_snapshots_snapshot_date'))
        batch_op.drop_index(batch_op.f('ix_dashboard_daily_snapshots_id'))

    op.drop_table('dashboard_daily_snapshots')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_id_number'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_categories_id'))

    op.drop_table('categories')
    with op.batch_alter_table('cash_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cash_sessions_id'))
        batch_op.drop_index(batch_op.f('ix_cash_sessions_date'))

    op.drop_table('cash_sessions')
    with op.batch_alter_table('cabys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cabys_code'))

    op.drop_table('cabys')
    op.drop_table('ai_config')
    # ### end Alembic commands ###
