"""add_common_cabys_code_to_sale_details

Revision ID: fb340249e5fa
Revises: g7b8c9d0e1f2
Create Date: 2026-05-27 11:27:14.283243

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb340249e5fa'
down_revision: Union[str, Sequence[str], None] = 'g7b8c9d0e1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('proforma_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_cabys_code', sa.String(length=20), nullable=True))

    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.add_column(sa.Column('common_cabys_code', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sale_details', schema=None) as batch_op:
        batch_op.drop_column('common_cabys_code')

    with op.batch_alter_table('proforma_details', schema=None) as batch_op:
        batch_op.drop_column('common_cabys_code')

    # ### end Alembic commands ###
