# app/constants/payment_methods.py

PAYMENT_METHOD_EFECTIVO = "Efectivo"
PAYMENT_METHOD_TARJETA = "Tarjeta"
PAYMENT_METHOD_CREDITO = "Crédito"
PAYMENT_METHOD_SINPE = "SINPE"  
PAYMENT_METHOD_TRANSFERENCIA = "Transferencia"  
PAYMENT_METHOD_OTRO = "Otro"

ALL_PAYMENT_METHODS = [
    PAYMENT_METHOD_EFECTIVO,
    PAYMENT_METHOD_TARJETA,
    PAYMENT_METHOD_TRANSFERENCIA,  
    PAYMENT_METHOD_SINPE,
    PAYMENT_METHOD_CREDITO,
    PAYMENT_METHOD_OTRO,
]